apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/deployments/pulsar-operator
    repoURL: https://gitlab.com/martijngonlag/local-stack.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
