apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarProxy
metadata:
    name: proxy
    namespace: pulsar
spec:
    brokerAddress: pulsar-broker-headless
    dnsNames: []
    #webSocketServiceEnabled: true
    image: streamnative/pulsar:2.10.2.4
    config:
      tls:
        enabled: false
    issuerRef:
      name: ""
    pod:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    replicas: 1
